### ISSUE TITLE
fingers is broken with non-standard default shell

### ISSUE THREAD

**Issue by Krakonos** [Morantron/tmux-fingers#18] opened 2017-01-26 20:54 UTC
I've been experimenting a little with tmux, tmux-fingers and fish (the friendly interactive shell). It seems that setting fish as my default shell in tmux ( ```set-option -g default-shell "/usr/bin/fish"``` ), running fingers doesn't seem to work. I don't get any error, just no functionality. I looked around a little, and didn't find any immediate cause. I'm using Arch linux, installed via tpm.

Any idea of what could be the cause?

Thanks!

**Comment by Morantron** [comment] 2017-01-27 08:03
Ooops, it is indeed broken. I'll look into it! Thanks :pray:

**Comment by Morantron** [comment] 2017-01-27 08:19
Sooo, the issue seems to be in [this line](https://github.com/Morantron/tmux-fingers/blob/d4f086de291ed6dc5759540675179453b5b62b75/scripts/tmux-fingers.sh#L7), where it is assumed that ENV variables for one command work the same across all shells. Looks like [this](https://fishshell.com/docs/current/faq.html#faq-single-env) needs to be done in fish instead. That particular function needs to be shell agnostic.

As a workaround, `0.3.2` version should work for you.

```sh
cd /path/to/tmux-fingers
git checkout 0.3.2
```

Make sure to checkout back to checkout back to master when this issue is closed!

**Comment by Morantron** [comment] 2017-02-14 07:31
fixed in `0.3.8`!

**Closed by Morantron** 2017-02-14 07:31 UTC
Labels: bug

**Comment by giulioungaretti** [comment] 2018-09-18 10:17
@Morantron I am getting the same error. Fingers appears for a split second and disappears.
It works if I change the shell to bash! Any way I can help to debug more ?

**Comment by Morantron** [comment] 2018-09-20 08:13
AFAIK it works with fish at least, which shell are you using @giulioungaretti ? Are you on latest tmux-fingers version? Running `/path/to/tmux/scripts/health-check.sh` can give some hints about what could be wrong

**Comment by giulioungaretti** [comment] 2018-09-20 12:53
@Morantron thanks for the quick answer!
Running:
 fish, version 2.7.1
Tmux 2.7
and last version of tmux-fingers (at least, doing an update from tpm.

Running the healt-check script I get a no errors and no output :D

**Comment by Morantron** [comment] 2018-09-20 14:50
Weird, I cannot reproduce it in the testing VM. Can you record a GIF or something of what's happening?

Was the plugin working for you previously? If so, you could try if previous version works for you:

```sh
cd ~/.tmux/plugins/tmux-fingers
git checkout 0.7.2
```

Thanks :pray:

**Comment by giulioungaretti** [comment] 2018-09-21 15:04
@Morantron this is really interesting: same configs, same versions BUT different OS (this time on MacOS, it works). Will investigate and try to record some footage.

**Comment by Morantron** [comment] 2018-09-26 10:30
super weeeiiird. You can try to record some video in arch linux with https://aur.archlinux.org/packages/peek-git/

Also, maybe you could try to add some logging

in `/path/to/tmux-fingers/tmux-fingers.tmux`

```diff
-tmux bind-key $FINGERS_KEY run-shell "$CURRENT_DIR/scripts/tmux-fingers.sh"
+tmux bind-key $FINGERS_KEY run-shell "$CURRENT_DIR/scripts/tmux-fingers.sh 2> $CURRENT_DIR/fingers-error.log"
```

And you should be able to see any errors in `/path/to/tmux-fingers/fingers-error.log`. I should add this logging on next release actually... :man_facepalming:
